pull_request_rules:
  - name: backport patches to cryostat-v2.2 branch
    conditions:
      - base=main
      - label=backport
    actions:
      backport:
        branches:
          - cryostat-v2.2
        assignees:
          - "{{ author }}"

  - name: auto label PRs from non-reviewers
    conditions:
      - author!=@reviewers
    actions:
      label:
        add:
          - needs-triage
