name: CI

on:
  push:
    branches:
      - main
      - v[0-9]+
      - v[0-9]+.[0-9]+
      - cryostat-v[0-9]+.[0-9]+
  pull_request:
    branches:
      - main
      - feature-.+
      - v[0-9]+
      - v[0-9]+.[0-9]+
      - cryostat-v[0-9]+.[0-9]+

jobs:
  prettier-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/*']
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
    - name: Use Node.js ${{ matrix.node-version }}
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - uses: bahmutov/npm-install@20216767ca67f0f7b4d095dc5859c5700a6581cb # 1.12.1
    - run: yarn format:check
  eslint-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/*']
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
    - name: Use Node.js ${{ matrix.node-version }}
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - uses: bahmutov/npm-install@20216767ca67f0f7b4d095dc5859c5700a6581cb # 1.12.1
    - run: yarn eslint:check --max-warnings 0
  type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/*']
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - uses: bahmutov/npm-install@20216767ca67f0f7b4d095dc5859c5700a6581cb # 1.12.1
      - run: yarn type-check
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/*']
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - uses: bahmutov/npm-install@20216767ca67f0f7b4d095dc5859c5700a6581cb # 1.12.1
    - run: yarn test:ci
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/*']
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - uses: bahmutov/npm-install@20216767ca67f0f7b4d095dc5859c5700a6581cb # 1.12.1
    - name: Setup firefox
      id: setup-firefox
      uses: browser-actions/setup-firefox@0bc507ddf224827e3b1af68e014d5e42ab93e795 # 1.7.2
      with:
        firefox-version: latest
    - name: Download geckodriver
      env:
        GECKODRIVER_VERSION: v0.33.0
      run: curl -sL https://github.com/mozilla/geckodriver/releases/download/${{env.GECKODRIVER_VERSION}}/geckodriver-${{env.GECKODRIVER_VERSION}}-linux64.tar.gz | tar xzvf -
    - name: Add to PATH
      run: sudo mv geckodriver /usr/local/bin
    - run: yarn itest:preview
