name: Clean up PR-scoped test images

on:
  pull_request_target:
    types:
      - closed

jobs:
  delete-images:
    name: Delete PR-scoped test images
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: r26d/ghcr-delete-image-action@9039322147055f1ee3f6359826701390d6b297aa # v1.4.1
        with:
          owner: ${{ github.repository_owner }}
          name: cryostat-web
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore-missing-package: true
          tag-regex: pr-${{ github.event.number }}-.*
          tagged-keep-latest: 0
        if: github.repository_owner == 'cryostatio'
