name: Generate Preview (PR)

concurrency:
  group: pr-${{ github.event.number }}
  cancel-in-progress: true

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

permissions: 
  pull-requests: write 

jobs:
  build-preview:
    runs-on: ubuntu-latest
    env:
      DEPLOY_DOMAIN: ${{ github.repository_owner }}-pr-${{ github.event.number }}.surge.sh
    steps:
    - name: Fail if safe-to-test label NOT applied
      if: ${{ !contains(github.event.pull_request.labels.*.name, 'safe-to-test') }}
      run: exit 1
    - uses: actions/checkout@v2
    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: 18
    - uses: bahmutov/npm-install@v1
    - name: Build assets
      run: yarn build:preview:notests
    - name: Publish to surge
      run: |
        npx surge --project ./dist --domain $DEPLOY_DOMAIN --token ${{ secrets.SURGE_TOKEN }}
    - name: Comment Preview URL
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: |-
          Preview is available: https://${{ env.DEPLOY_DOMAIN }}
